#!/usr/bin/env python

import os
import whisper_timestamped

CACHE_DIR = './weights'

# Ensure the cache directory exists
os.makedirs(CACHE_DIR, exist_ok=True)

# Download and save the model
model = whisper_timestamped.load_model(
    "large-v3",
    device="cpu",
    download_root=CACHE_DIR
)

print("Model weights downloaded successfully.")
print(f"Model weights are stored in: {CACHE_DIR}")